[build]
  command = "npm install @11ty/eleventy && ./node_modules/.bin/eleventy"
  publish = "_site"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
